### ISSUE TITLE
class_error: 100.00

### ISSUE THREAD

**Issue by deepinact** [tgxs002/CORA#11]
Hello, I have met a problem. The class_error in the test phase is always 100, and I can do nothing to change this.

**Comment by deepinact** [comment]
<img width="1523" alt="image" src="https://github.com/tgxs002/CORA/assets/43721507/e39d2ab8-6fa4-4183-ba46-3c1aa4105487">

**Comment by JunL-Geek** [comment]
You should set bigger batchsize, this works for me

**Comment by Noraaa1** [comment]
hello, I encountered the same issue. Have you solved it?

**Comment by doilion** [comment]
Hello, I also encountered the same issue. How did you finally resolve it? Did you follow the original poster's suggestion to increase the batch_size?
