### ISSUE TITLE
question about the ckeckpoints

### ISSUE THREAD

**Issue by xiaomabufei** [tgxs002/CORA#15]
the issue appears, when i load the COCO_RN50 checkpoints:
Error(s) in loading state_dict for FastDETR:
	Missing key(s) in state_dict: "input_proj.0.1.weight", "input_proj.0.1.bias".

**Comment by xiaomabufei** [comment]
I have solve this problem. Thanks for your contribution.

**Comment by myl-uestc** [comment]
> I have solve this problem. Thanks for your contribution.

how do you solve this problem
