### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by eternaldolphin** [tgxs002/CORA#4]
![image](https://user-images.githubusercontent.com/55774463/231992282-5b0b6b6c-6443-43b6-9ec6-ec26ee53888e.png)
It seems that the code lacks some data filtration?

**Comment by tgxs002** [comment]
You should be able to fix it with larger batch size.

**Comment by eternaldolphin** [comment]
Thank you (and voice out poverty

**Comment by davidyang180** [comment]
> You should be able to fix it with larger batch size.

If the memory is limited, does adding a very small number (float("1e-8")) compensation to the denominator part affect the model training?

**Comment by qjh666888** [comment]
Are there any other methods besides adjusting the batch
